# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e989c78480dec35c9b70b905e764bb53ae7373b85464eb0bcad0fd8a38e0972bd8e068ebc39da681c72ad40ed40883f82911f4117665f6c3283192c1c4f8fcd6

test:
  secret_key_base: 482d2c8388542102fa164db9a7388ae8bc9815af7ca876628df6f0be2b3b7a23b0dbc8afd95b08913e035954e7f08e452c0e27e1becfddb375ef36d98833dc33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
